version: '3'
services:
  java:
    container_name: week10c
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mysql
    container_name: mysql-we
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=fruitshop